version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - /etc/letsencrypt
    links:
      - redis
    environment:
      REDIS_URL: 'redis://redis:6379'
      PORT: 443
      CALLBACK_ENV: 'https://www.setbuilder.app'
      VIRTUAL_HOST: setbuilder.app,www.setbuilder.app
      VIRTUAL_PROTO: https
      VIRTUAL_PORT: 443
      LETSENCRYPT_HOST: setbuilder.app
      LETSENCRYPT_EMAIL: brad.spaulding@gmail.com
  redis:
    image: redis:alpine
